sns:
  label: 社交资料
  items:
    rss:
      name: rss
      label: RSS
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    twitter:
      name: twitter
      label: Twitter
      type: text
      placeholder: '只需填入 Twitter 用户名即可'
    facebook:
      name: facebook
      label: Facebook
      type: text
      placeholder: '只需填入 Facebook 用户名即可'
    instagram:
      name: instagram
      label: Instagram
      type: text
      placeholder: '只需填入 Instagram 用户名即可'
    dribbble:
      name: dribbble
      label: Dribbble
      type: text
      placeholder: '只需填入 Dribbble 用户名即可'
    weibo:
      name: weibo
      label: 微博
      type: text
      placeholder: '只需填入微博 Id 即可'
    email:
      name: email
      label: Email
      type: text
      placeholder: '只需填入邮箱地址即可'
    github:
      name: github
      label: Github
      type: text
      placeholder: '只需填入 Github 用户名即可'
    qq:
      name: qq
      label: QQ
      type: text
      placeholder: '只需填入 QQ 号即可'
    telegram:
      name: telegram
      label: Telegram
      type: text
      placeholder: '只需填入 Telegram Id 即可'
style:
  label: 样式设置
  items:
    icon:
      name: icon
      label: 右上角图标
      type: attachment
    post_title_upper:
      name: post_title_upper
      label: 文章标题大写
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    blog_title_upper:
      name: blog_title_upper
      label: 博客标题大写
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    avatar_circle:
      name: avatar_circle
      label: 圆形头像
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    hitokoto:
      name: hitokoto
      label: 博客描述开启一言
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    google_color:
      name: google_color
      label: 浏览器沉浸颜色
      type: color
      default: '#fff'
    scrollbar:
      name: scrollbar
      label: 全局滚动条颜色
      type: color
      default: '#3798e8'
    code_pretty:
      name: code_pretty
      label: 文章代码高亮主题
      type: select
      default: ''
      options:
        - value: ''
          label: '无'
        - value: '-coy'
          label: 'Coy'
        - value: '-dark'
          label: 'Dark'
        - value: '-funky'
          label: 'Funky'
        - value: '-okaidia'
          label: 'Okaidia'
        - value: '-solarizedlight'
          label: 'Solarized Light'
        - value: '-tomorrow'
          label: 'Tomorrow'
        - value: '-twilight'
          label: 'Twilight'
