apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-anatole-setting
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: select
          name: sidebar_width
          label: 侧边栏宽度
          value: 40%
          options:
            - value: 20%
              label: 20%
            - value: 30%
              label: 30%
            - value: 40%
              label: 40%
            - value: 50%
              label: 50%
        - $formkit: attachment
          name: sidebar_background
          label: 侧边栏背景图
        - $formkit: attachment
          name: icon
          label: 右上角图标
        - $formkit: radio
          name: avatar_circle
          label: 圆形头像
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: katex
          label: KaTex 公式渲染
          value: false
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
    - group: social_media
      label: 社交资料
      formSchema:
        - $formkit: repeater
          name: items
          label: 社交媒体
          value: []
          children:
            - $formkit: select
              name: icon
              label: 图标
              options:
                - label: RSS
                  value: i-mdi-rss
                - label: Twitter
                  value: i-mdi-twitter
                - label: Facebook
                  value: i-mdi-facebook
                - label: Instagram
                  value: i-mdi-instagram
                - label: Dribbble
                  value: i-mdi-dribbble
                - label: 新浪微博
                  value: i-mdi-sina-weibo
                - label: QQ
                  value: i-mdi-qqchat
                - label: Telegram
                  value: i-mdi-telegram
                - label: 电子邮箱
                  value: i-mdi-email
                - label: GitHub
                  value: i-mdi-github
            - $formkit: text
              name: name
              label: 名称
            - $formkit: text
              name: url
              label: 链接
              validation: "required"
