apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-anatole
  annotations:
    # Add supports for Halo App Store
    # https://www.halo.run/store/apps/app-KcHZz
    "store.halo.run/app-id": "app-KcHZz"
spec:
  displayName: Anatole
  author:
    name: Caicai
    website: https://www.caicai.me
  website: https://github.com/halo-dev/halo-theme-anatole
  repo: https://github.com/halo-dev/halo-theme-anatole
  settingName: theme-anatole-setting
  configMapName: theme-anatole-configMap
  version: 2.1.0
  requires: ">=2.2.0"
